channles:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - tqdm==4.65.0
    - flask==2.2.2
    - opencv-python-headless
    - numpy==1.24.2
    - torch
    - torchvision
    - streamlit
    - pandas